FROM inemo/syntaxnet_base

# Common locale: en_EN.UTF-8
ENV LANG_LOCALE="<%PLACEHOLDER_LANG_LOCALE%>"

# Common url: http://download.tensorflow.org/models/parsey_universal/English.zip
ENV MODEL_URL="<%PLACEHOLDER_MODEL_URL%>"

# E.g.: English.zip
ENV MODEL_NAME="<%PLACEHOLDER_MODEL_NAME%>"

######################################

# Setting up locales for the target language

RUN \
echo "$LANG_LOCALE" > /etc/locale.gen && \
locale-gen "$LANG_LOCALE" && \
echo 'LANG="$LANG_LOCALE"'>/etc/default/locale && \
dpkg-reconfigure --frontend=noninteractive locales && \
update-locale LC_ALL="$LANG_LOCALE" LANG="$LANG_LOCALE"  

ENV LANG "$LANG_LOCALE"

# Downloading and unpacking model for Russian

ADD "$MODEL_URL" /root/models/syntaxnet/syntaxnet/models/Model.zip
RUN unzip "/root/models/syntaxnet/syntaxnet/models/Model.zip" -d /root/models/syntaxnet/syntaxnet/models/Model/ && \
mv /root/models/syntaxnet/syntaxnet/models/Model/$(ls /root/models/syntaxnet/syntaxnet/models/Model/ | head -1) \
/root/models/syntaxnet/syntaxnet/models/Model1 && \
rm -r /root/models/syntaxnet/syntaxnet/models/Model/

# Standalone server

COPY api /root/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/api/

######################################

WORKDIR /root/models/syntaxnet/

CMD ./syntaxnet/models/parsey_universal/parse.sh ./syntaxnet/models/Model1

